### ISSUE TITLE
Cleanup fails with cattrs.errors.StructureHandlerNotFoundError: Unsupported type: 'Optional[str]'. Register a structure hook for it.

### ISSUE THREAD

**Issue by lloesche** [someengineering/resoto#1119]
### Description

```
22-08-23 18:06:54|resotoworker|DEBUG|6391|resoto.worker-collector_0  Received message of kind action, type cleanup, data: {'task': '9b64a4a6-22fd-11ed-b6be-0ce441e0daff', 'step': 'cleanup'}
22-08-23 18:06:54|resotoworker| INFO|6391|resoto.worker-collector_0  Running cleanup
22-08-23 18:06:54|resotoworker|DEBUG|6391|resoto.worker-collector_0  Sending search /desired.clean == true and /metadata.cleaned != true and /metadata.protected!=true and /ancestors.cloud.reported.id in ["aws"] <-default,delete[0:]->
22-08-23 18:06:55|resotoworker|ERROR|6391|resoto.worker-collector_0  Failed to cleanup: Unsupported type: 'Optional[str]'. Register a structure hook for it.
Traceback (most recent call last):
  File "/Users/lukas/repo/resoto/resotoworker/resotoworker/__main__.py", line 213, in core_actions_processor
    cleanup(
  File "/Users/lukas/repo/resoto/resotoworker/resotoworker/cleanup.py", line 34, in cleanup
    graph = cg.graph(search)
  File "/Users/lukas/repo/resoto/resotolib/resotolib/core/search.py", line 98, in graph
    process_data_line(data, graph)
  File "/Users/lukas/repo/resoto/resotolib/resotolib/core/search.py", line 79, in process_data_line
    node = node_from_dict(data)
  File "/Users/lukas/repo/resoto/resotolib/resotolib/core/model_export.py", line 407, in node_from_dict
    node = converter.structure_attrs_fromdict(new_node_data, node_type)
  File "/Users/lukas/repo/resoto/venv/lib/python3.10/site-packages/cattrs/converters.py", line 452, in structure_attrs_fromdict
    conv_obj[name] = self._structure_attribute(a, val)
  File "/Users/lukas/repo/resoto/venv/lib/python3.10/site-packages/cattrs/converters.py", line 428, in _structure_attribute
    return self._structure_func.dispatch(type_)(value, type_)
  File "/Users/lukas/repo/resoto/venv/lib/python3.10/site-packages/cattrs/converters.py", line 346, in _structure_error
    raise StructureHandlerNotFoundError(msg, type_=cl)
cattrs.errors.StructureHandlerNotFoundError: Unsupported type: 'Optional[str]'. Register a structure hook for it.
22-08-23 18:06:55|resotoworker|DEBUG|6391|resoto.worker-collector_0  Sending reply {'kind': 'action_error', 'message_type': 'cleanup', 'data': {'task': '9b64a4a6-22fd-11ed-b6be-0ce441e0daff', 'step': 'cleanup'}}
```

It was working 7min earlier and there was no collect run in between. Wondering what caused this.

### Version

3.0.0a0

**Comment by aquamatthias** [comment]
Fixed via #1126
