### ISSUE TITLE
[digitalocean] Scheme and Hostname missing in volume collect

### ISSUE THREAD

**Issue by lloesche** [someengineering/resoto#1590]
### Description

```
Traceback (most recent call last):
  File "/usr/local/resoto-venv-python3/lib/python3.11/site-packages/resoto_plugin_digitalocean/__init__.py", line 75, in collect_team
    dopc.collect()
  File "/usr/local/resoto-venv-python3/lib/python3.11/site-packages/resoto_plugin_digitalocean/collector.py", line 244, in collect
    collector()
  File "<decorator-gen-12>", line 2, in collect_volumes
  File "/usr/local/resoto-venv-python3/lib/python3.11/site-packages/prometheus_client/context_managers.py", line 83, in wrapped
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/resoto-venv-python3/lib/python3.11/site-packages/resoto_plugin_digitalocean/collector.py", line 558, in collect_volumes
    volumes = self.client.list_volumes()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/resoto-venv-python3/lib/python3.11/site-packages/resoto_plugin_digitalocean/client.py", line 160, in list_volumes
    return self._fetch("/volumes", "volumes")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/resoto-venv-python3/lib/python3.11/site-packages/retrying.py", line 56, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/resoto-venv-python3/lib/python3.11/site-packages/retrying.py", line 257, in call
    return attempt.get(self._wrap_exception)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/resoto-venv-python3/lib/python3.11/site-packages/retrying.py", line 301, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/resoto-venv-python3/lib/python3.11/site-packages/six.py", line 719, in reraise
    raise value
  File "/usr/local/resoto-venv-python3/lib/python3.11/site-packages/retrying.py", line 251, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
                      ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/resoto-venv-python3/lib/python3.11/site-packages/resoto_plugin_digitalocean/client.py", line 110, in _fetch
    json_response = validate_status(requests.get(url, headers=self.headers, allow_redirects=True)).json()
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/resoto-venv-python3/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/resoto-venv-python3/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/resoto-venv-python3/lib/python3.11/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/resoto-venv-python3/lib/python3.11/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/resoto-venv-python3/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/resoto-venv-python3/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '/v2/volumes?page=2&per_page=200': No scheme supplied. Perhaps you meant https:///v2/volumes?page=2&per_page=200?
```

### Version

3.4

**Comment by meln1k** [comment]
fixed by https://github.com/someengineering/resoto/pull/1592
