### ISSUE TITLE
[resotocore] task_timeout_watcher caught an exception: Command >start_task< is not known

### ISSUE THREAD

**Issue by tdickers** [someengineering/resoto#733]
### Description

It looks like `check_overdue_tasks` is failing because the `start_task` command is not found. Haven't looked at the code yet, but I believe this needs to be updated to use `workflow run`. This is generating some very long and repetitive stack traces that end in `resotocore.error.CLIParseError: Command >start_task< is not known. typo?`

I believe this occurred after a long-running task. Apologies for lack of confirmation via reading the code - it's the end of the day.

### Version

2.0.0a19

### Environment

Official Resoto Docker image (repackaged verbatim) on Kubernetes 

### Steps to Reproduce

1. Have a long-running task (I think) exceed timeout
2. See the error in the logs after `task_timeout_watcher` kicks in

### Logs

```shell
22-03-24 22:42:01|resotocore|ERROR|86|MainThread  Periodic function task_timeout_watcher caught an exception: Command >start_task< is not known. typo?
Traceback (most recent call last):
(next 8 lines are repeated many times)
  File "/usr/local/resoto-venv-pypy3/lib/pypy3.8/site-packages/resotocore/task/task_handler.py", line 493, in check_overdue_tasks
    await task.update_task
  File "/usr/local/pypy/lib/pypy3.8/asyncio/futures.py", line 263, in __await__
    return self.result()  # May raise too.
  File "/usr/local/pypy/lib/pypy3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/local/resoto-venv-pypy3/lib/pypy3.8/site-packages/resotocore/util.py", line 331, in _run
    await result
  File "/usr/local/resoto-venv-pypy3/lib/pypy3.8/site-packages/resotocore/task/task_handler.py", line 493, in check_overdue_tasks
    await task.update_task
  File "/usr/local/pypy/lib/pypy3.8/asyncio/futures.py", line 263, in __await__
    return self.result()  # May raise too.
  File "/usr/local/pypy/lib/pypy3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/local/pypy/lib/pypy3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/usr/local/resoto-venv-pypy3/lib/pypy3.8/site-packages/resotocore/task/task_handler.py", line 426, in execute_commands
    result = await self.cli.execute_cli_command(command.command, stream.list, ctx)
  File "/usr/local/resoto-venv-pypy3/lib/pypy3.8/site-packages/resotocore/cli/cli.py", line 461, in execute_cli_command
    return [await parsed.to_sink(sink) for parsed in await self.evaluate_cli_command(cli_input, ctx, True)]
  File "/usr/local/resoto-venv-pypy3/lib/pypy3.8/site-packages/resotocore/cli/cli.py", line 457, in evaluate_cli_command
    res = [await parse_line(cmd_line) for cmd_line in command_lines]
  File "/usr/local/resoto-venv-pypy3/lib/pypy3.8/site-packages/resotocore/cli/cli.py", line 457, in <listcomp>
    res = [await parse_line(cmd_line) for cmd_line in command_lines]
  File "/usr/local/resoto-venv-pypy3/lib/pypy3.8/site-packages/resotocore/cli/cli.py", line 414, in parse_line
    ctx, commands = await combine_query_parts([self.command(c.cmd, c.args, ctx) for c in parsed.commands], ctx)
  File "/usr/local/resoto-venv-pypy3/lib/pypy3.8/site-packages/resotocore/cli/cli.py", line 414, in <listcomp>
    ctx, commands = await combine_query_parts([self.command(c.cmd, c.args, ctx) for c in parsed.commands], ctx)
  File "/usr/local/resoto-venv-pypy3/lib/pypy3.8/site-packages/resotocore/cli/cli.py", line 273, in command
    raise CLIParseError(f"Command >{name}< is not known. typo?")
resotocore.error.CLIParseError: Command >start_task< is not known. typo?
```

**Comment by aquamatthias** [comment]
Thanks, @tdickers for the report.

The `start_task` command has been removed and replaced by the `workflows` command (#535).
I will take a look at why a failing command needs to be picked up by the overdue watcher.

**Comment by aquamatthias** [comment]
With above fix in place, the log looks like this:
```
22-03-25 10:58:00|resotocore| INFO|91188|MainThread  Task 0dae6004-ac22-11ec-afc5-dad780437c54: begin step is: execute
22-03-25 10:58:00|resotocore| INFO|91188|MainThread  Start new task: start_task with id 0dae6004-ac22-11ec-afc5-dad780437c54
22-03-25 10:58:00|resotocore|WARNING|91188|MainThread  Command start_task foo failed with error: Command >start_task< is not known. typo?
22-03-25 10:58:00|resotocore| INFO|91188|MainThread  Task 0dae6004-ac22-11ec-afc5-dad780437c54: begin step is: task_end
```
